### ISSUE TITLE
博主你的xiu-search 项目无法提问啊，在进行爬虫就报错了 

### ISSUE THREAD

**Issue by zq19940507** [Justin3go/FouTou#1]
报错内容
Traceback (most recent call last):
  File "G:\code\anaconda\envs\xiu_search\lib\site-packages\fake_useragent\utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "G:\code\anaconda\envs\xiu_search\lib\site-packages\fake_useragent\utils.py", line 99, in get_browsers
    html = html.split('<table class="w3-table-all notranslate">')[1]
IndexError: list index out of range
Traceback (most recent call last):
  File "G:\code\anaconda\envs\xiu_search\lib\site-packages\fake_useragent\utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "G:\code\anaconda\envs\xiu_search\lib\site-packages\fake_useragent\utils.py", line 99, in get_browsers
    html = html.split('<table class="w3-table-all notranslate">')[1]
IndexError: list index out of range

**Comment by Justin3go** [comment]
应该是fake_useragent没使用对，你去搜搜，像这样：https://stackoverflow.com/questions/68772211/fake-useragent-module-not-connecting-properly-indexerror-list-index-out-of-ra

**Comment by Justin3go** [comment]
可以直接邮件联系，这个Iusse我先关了
